services:
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: wsl_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: wsl_redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq
    container_name: rabbitmq_server
    restart: always
    ports:
      - "${RABBITMQ_SERVER_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PLUGIN_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_lib:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  mysql_data:
  redis_data:
  rabbitmq_lib:
    driver: local
  rabbitmq_log:
    driver: local